version: "3.9"

services:
    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - "5050:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin

networks:
    default:
        external: true
        name: server_default

volumes:
    pgadmin-data: